import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../server/app.js';
const input = { title: '팀 회의', description: '', startDate: '2026-10-10', endDate: '2026-10-11', startMinute: 540, endMinute: 1080, duration: 180, placeMode: 'together' };
test('실제 HTTP: 인증, 참여자 격리, 투표 수정, 서버 권한, 설정 변경과 영구 저장', async t => {
  const dir = mkdtempSync(join(tmpdir(), 'moimpyo-test-')), dbPath = join(dir, 'test.sqlite');
  let instance = createApp({ dbPath }); let server = instance.app.listen(0, '127.0.0.1'); await new Promise(r => server.once('listening', r));
  let base = `http://127.0.0.1:${server.address().port}`;
  const client = () => { const cookies = {}; return { async request(path, method = 'GET', body, extra = {}) { const r = await fetch(base + '/api' + path, { method, headers: { 'Content-Type': 'application/json', 'X-Moimpyo': '1', Cookie: Object.entries(cookies).map(([k,v]) => `${k}=${v}`).join('; '), ...extra }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); for (const c of r.headers.getSetCookie()) { const [k,v] = c.split(';')[0].split('='); cookies[k] = v; assert.match(c, /HttpOnly/); assert.match(c, /SameSite=Lax/); } return { status: r.status, body: await r.json() }; } }; };
  t.after(async () => { await new Promise(r => server.close(r)); instance.db.close(); rmSync(dir, { recursive: true, force: true }); });
  const owner = client(), other = client(), guest1 = client(), guest2 = client();
  assert.equal((await guest1.request('/meetings', 'POST', input)).status, 401);
  assert.equal((await owner.request('/auth/register', 'POST', { name:'주최자',email:'owner@example.com',password:'password12345' })).status, 200);
  const mid = (await owner.request('/meetings', 'POST', input)).body.id, path = '/meetings/' + mid;
  const initial = (await guest1.request(path)).body;
  assert.equal(initial.result.total, 0); assert.deepEqual(initial.result.common, []); assert.equal(initial.isOwner, false);
  assert.equal((await guest1.request(path + '/response', 'PUT', { name:'민수', slots:['2026-10-10/540','2026-10-10/570'], revision:1 })).status, 200);
  assert.equal((await guest2.request(path)).body.mine, null);
  await guest2.request(path + '/response', 'PUT', { name:'민수', slots:['2026-10-10/600'], revision:1 });
  assert.equal((await owner.request(path)).body.result.total, 2);
  await guest1.request(path + '/response', 'PUT', { name:'민수', slots:['2026-10-10/540'], revision:1, participantId:'forged' });
  assert.deepEqual((await guest2.request(path)).body.mine.slots, ['2026-10-10/600']);
  assert.equal((await guest1.request(path + '/response', 'PUT', { name:'민수',slots:['2026-10-10/541'],revision:1 })).status, 400);
  assert.equal((await guest1.request(path + '/finalize/time', 'POST', {date:'2026-10-10',start:540,revision:1})).status, 401);
  await other.request('/auth/register', 'POST', {name:'다른 주최자',email:'other@example.com',password:'password12345'});
  for (const [suffix, method, body] of [['', 'PATCH', {...input,revision:1}], ['/finalize/time','POST',{date:'2026-10-10',start:540,revision:1}], ['/finalize/place','POST',{placeId:'fake',revision:1}], ['/reopen/time','POST',{revision:1}]]) assert.equal((await other.request(path + suffix, method, body)).status, 403);
  assert.equal((await guest1.request(path + '/places', 'POST', {name:'민수',revision:1,place:{name:'카페',address:'javascript:alert(1)'}})).status, 400);
  await guest1.request(path + '/places', 'POST', {name:'민수',revision:1,place:{name:'카페',address:'https://example.com/map',note:'조용해요'}});
  await guest2.request(path + '/places', 'POST', {name:'민수',revision:1,place:{name:'회의실',address:'서울 성북구 정릉로 77'}});
  const places = (await owner.request(path)).body.places;
  assert.equal((await guest1.request(path + '/places', 'POST', {name:'민수',revision:1,place:{name:'주소 없는 후보'}})).status,400);
  assert.equal((await guest1.request(path)).body.places.find(p=>p.id===places[0].id).canEdit,true);
  assert.equal((await owner.request(path)).body.places[0].canEdit,false);
  assert.equal((await owner.request(path + '/places/' + places[0].id,'PATCH',{revision:1,place:{name:'위조',address:'서울'}})).status,403);
  assert.equal((await guest2.request(path + '/places/' + places[0].id,'DELETE',{revision:1})).status,403);
  assert.equal((await guest1.request(path + '/places/' + places[0].id,'PATCH',{revision:1,place:{name:'카페',address:'서울 성북구 정릉로 77',note:'수정'}})).status,200);
  await guest1.request(path + '/places','POST',{name:'민수',revision:1,place:{name:'삭제 확인',address:'서울'}});
  const disposable = (await guest1.request(path)).body.places.find(p=>p.name==='삭제 확인');
  await guest2.request(path + '/votes','PUT',{name:'민수',revision:1,places:[disposable.id]});
  assert.equal((await guest1.request(path + '/places/' + disposable.id,'DELETE',{revision:1})).status,200);
  assert.deepEqual((await guest2.request(path)).body.myVotes,[]);
  await guest1.request(path + '/votes', 'PUT', {name:'민수',revision:1,places:places.map(p=>p.id)});
  await guest2.request(path + '/votes', 'PUT', {name:'민수',revision:1,places:[places[0].id]});
  assert.equal((await owner.request(path)).body.places[0].count, 2);
  await guest1.request(path + '/votes', 'PUT', {name:'민수',revision:1,places:[places[1].id]});
  assert.deepEqual((await guest2.request(path)).body.myVotes, [places[0].id]);
  assert.equal((await owner.request(path + '/finalize/place','POST',{placeId:places[0].id,revision:1})).status,200);
  const partial = (await guest1.request(path)).body;
  assert.equal(partial.meeting.finalizedTime,null); assert.equal(partial.meeting.finalizedPlace.name,'카페');
  assert.equal((await guest1.request(path + '/votes','PUT',{name:'민수',revision:2,places:[]})).status,409);
  assert.equal((await owner.request(path + '/finalize/time','POST',{date:'2026-10-10',start:1050,revision:2})).status,400);
  assert.equal((await owner.request(path + '/finalize/time','POST',{date:'2026-10-10',start:540,revision:2})).status,200);
  assert.equal((await owner.request(path,'PATCH',{...input,startMinute:600,revision:3})).status,409);
  assert.equal((await owner.request(path,'PATCH',{...input,startMinute:600,revision:3,acknowledge:true})).status,200);
  const changed = (await guest1.request(path)).body;
  assert.equal(changed.mine.outsideCount,1); assert.equal(changed.meeting.finalizedTime,null); assert.ok(changed.meeting.finalizedPlace);
  assert.equal((await guest1.request(path + '/response','PUT',{name:'민수',slots:[],revision:1})).status,409);
  await guest1.request(path + '/response','PUT',{name:'민수',slots:['2026-10-10/630'],revision:4});
  assert.ok((await guest1.request(path)).body.mine.slots.includes('2026-10-10/540'));
  assert.equal((await owner.request(path,'PATCH',{...input,revision:4,acknowledge:true},{Origin:'https://evil.example'})).status,403);
  await new Promise(r => server.close(r)); instance.db.close();
  instance = createApp({ dbPath }); server = instance.app.listen(0,'127.0.0.1'); await new Promise(r => server.once('listening',r)); base = `http://127.0.0.1:${server.address().port}`;
  const persisted = (await owner.request(path)).body;
  assert.equal(persisted.result.total,2); assert.equal(persisted.places.length,2); assert.ok(persisted.isOwner); assert.equal(persisted.meeting.finalizedPlace.name,'카페');
  await owner.request('/logout','POST',{}); assert.equal((await owner.request('/meetings')).status,401);
  assert.equal((await owner.request('/auth/login','POST',{email:'owner@example.com',password:'wrongpassword'})).status,401);
  assert.equal((await owner.request('/auth/login','POST',{email:'owner@example.com',password:'password12345'})).status,200);
  assert.equal((await guest1.request('/meetings/bad-link')).status,404);
  // Entering creates an unanswered participant, without inventing an availability response.
  const visitor = client();
  assert.equal((await visitor.request(path + '/join','POST',{})).status,200);
  const joined = (await visitor.request(path)).body;
  assert.equal(joined.mine.slots,null);
  assert.equal(joined.result.total,2);
  assert.equal(joined.participants.find(p=>p.isMine).responded,false);
  assert.equal((await visitor.request(path + '/join','POST',{})).status,200);
  assert.equal((await visitor.request(path)).body.participants.length,joined.participants.length);
  assert.equal((await visitor.request(path + '/participants/me','PATCH',{name:'새 이름',participantId:joined.participants[0].id})).status,200);
  assert.equal((await visitor.request(path)).body.mine.name,'새 이름');
  assert.equal((await guest1.request(path)).body.mine.name,'민수');
  assert.equal((await visitor.request(path + '/participants/me','PATCH',{name:' '})).status,400);
  const removePath = path + '/participants/' + joined.mine.id + '/remove';
  assert.equal((await other.request(removePath,'POST',{revision:4})).status,403);
  assert.equal((await owner.request(removePath,'POST',{revision:4})).status,200);
  assert.equal((await visitor.request(path + '/join','POST',{})).status,403);
  assert.equal((await visitor.request(path + '/response','PUT',{name:'재입장',slots:[],revision:4})).status,403);
  const guest2Id = (await guest2.request(path)).body.mine.id;
  assert.equal((await owner.request(path + '/participants/' + guest2Id + '/remove','POST',{revision:4})).status,200);
  const removed = (await owner.request(path)).body;
  assert.equal(removed.result.total,1);
  assert.equal(removed.places.find(p=>p.id===places[0].id).count,0);
  await owner.request(path + '/join','POST',{});
  const ownerId = (await owner.request(path)).body.mine.id;
  assert.equal((await owner.request(path + '/participants/' + ownerId + '/remove','POST',{revision:4})).status,400);
  assert.equal((await owner.request(path + '/finalize/time','POST',{date:'2026-10-10',start:600,revision:4})).status,200);
  assert.equal((await owner.request(path + '/finalize/time','POST',{date:'2026-10-10',start:630,revision:5})).status,200);
  assert.equal((await owner.request(path)).body.meeting.finalizedTime.start,630);
  assert.equal((await guest1.request(path + '/response','PUT',{name:'민수',slots:['2026-10-10/630'],revision:6})).status,200);
  const afterFinalResponse = (await guest1.request(path)).body;
  assert.ok(afterFinalResponse.mine.slots.includes('2026-10-10/630'));
  assert.equal(afterFinalResponse.meeting.finalizedTime.start,630);
  // Deletion is owner-only, revision-checked, and cleans up only this meeting.
  const kept = (await owner.request('/meetings', 'POST', input)).body.id;
  // A signed-in participant sees joined meetings, but unrelated meetings stay private.
  assert.deepEqual((await other.request('/meetings')).body, []);
  await other.request(path + '/join', 'POST', {});
  const participantList = (await other.request('/meetings')).body;
  assert.deepEqual(participantList.map(m => [m.id, m.isOwner]), [[mid, false]]);
  const ownerList = (await owner.request('/meetings')).body;
  assert.equal(ownerList.filter(m => m.id === mid).length, 1);
  assert.ok(ownerList.every(m => m.isOwner));
  const otherParticipant = (await other.request(path)).body.mine.id;
  await owner.request(path + '/participants/' + otherParticipant + '/remove', 'POST', { revision:6 });
  assert.deepEqual((await other.request('/meetings')).body, []);
  assert.equal((await guest1.request(path, 'DELETE', {revision:6})).status,401);
  assert.equal((await other.request(path, 'DELETE', {revision:6})).status,403);
  assert.equal((await owner.request(path, 'DELETE', {revision:1})).status,409);
  assert.equal((await owner.request(path)).status,200);
  assert.equal((await owner.request(path, 'DELETE', {revision:6})).status,200);
  assert.equal((await owner.request(path)).status,404);
  assert.equal((await guest1.request(path + '/join','POST',{})).status,404);
  assert.equal((await owner.request('/meetings/' + kept)).status,200);
  assert.deepEqual((await owner.request('/meetings')).body.map(m=>m.id),[kept]);
  for (const table of ['participants','places','removed_participants']) {
    assert.equal(instance.db.prepare(`SELECT COUNT(*) AS n FROM ${table} WHERE meeting=?`).get(mid).n,0);
  }
  assert.equal(instance.db.prepare('SELECT COUNT(*) AS n FROM votes').get().n,0);
  assert.equal((await owner.request(path, 'DELETE', {revision:6})).status,404);
});
