import { test, expect } from '@playwright/test';
test('주최자와 별도 모바일 브라우저: 생성, 드래그, 응답 수정, 투표, 독립 확정', async ({ page, browser }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.clock.setFixedTime(new Date('2026-10-03T03:00:00Z'));
  await page.goto('/'); await expect(page.getByRole('heading', { name: '쉬운 약속 정하기 클릭 한번에-!' })).toBeVisible();
  await page.screenshot({ path: 'test-results/home-desktop.png', fullPage: true });
  await page.getByRole('link', { name: '새 모임 만들기' }).click();
  await page.getByRole('button', { name: '처음 오셨나요? 계정 만들기' }).click();
  await page.getByLabel('이름', { exact: true }).fill('지수');
  await page.getByLabel('아이디', { exact: true }).fill(`host-${Date.now()}@example.com`);
  await page.getByLabel('비밀번호', { exact: true }).fill('securepassword123');
  await page.getByRole('button', { name: '계정 만들기', exact: true }).click();
  await expect(page.getByRole('heading', { name: '어떤 모임인가요?' })).toBeVisible();
  await page.getByLabel('모임 이름').fill('금요일, 우리 저녁 먹어요');
  await page.getByLabel('간단한 설명').fill('오랜만에 얼굴 보고 이야기해요. 편한 시간을 남겨 주세요.');
  await page.getByRole('button', { name: '선택 모두 해제', exact: true }).click();
  for (const date of ['2026-10-09','2026-10-10','2026-10-11']) await page.getByRole('button', {name:date,exact:true}).click();
  await page.getByRole('combobox', {name:'시작 시간', exact:true}).selectOption('840'); await page.getByRole('combobox', {name:'마지막 시간', exact:true}).selectOption('1200');
  await page.getByRole('combobox', {name:'예상 소요 시간', exact:true}).selectOption('120');
  await page.getByRole('button', { name: '모임 만들기', exact:true }).click();
  await expect(page.getByRole('heading', { name:'금요일, 우리 저녁 먹어요' })).toBeVisible();
  const url = page.url();
  await page.screenshot({ path:'test-results/meeting-empty-desktop.png', fullPage:true });
  await page.getByRole('link', { name:'시간 정하기' }).click();
  await expect(page.getByRole('button', { name:'전체 현황', exact:true })).toHaveAttribute('aria-pressed','true');
  const first = page.locator('[data-slot="2026-10-09/840"]'), last = page.locator('[data-slot="2026-10-09/930"]');
  await last.scrollIntoViewIfNeeded();
  const a = await first.boundingBox(), b = await last.boundingBox();
  await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2); await page.mouse.down(); await page.mouse.move(b.x + b.width / 2, b.y + b.height / 2, { steps:12 }); await page.mouse.up();
  for (const t of [840,870,900,930]) await expect(page.locator(`[data-slot="2026-10-09/${t}"]`)).toHaveAttribute('aria-pressed','true');
  await expect(page.getByText('내 가능 시간이 자동 저장되었어요.')).toBeVisible();
  const mobile = await browser.newContext({ viewport:{ width:390,height:844 }, isMobile:true, hasTouch:true });
  const guest = await mobile.newPage(); guest.on('pageerror', e => errors.push(e.message));
  await guest.goto(url); await guest.getByLabel('내 이름',{exact:true}).fill('민수'); await guest.getByRole('button',{name:'이 이름으로 참여하기',exact:true}).click(); await guest.getByRole('link',{name:'시간 정하기'}).click();
  for(const t of [840,870,900,930]) await guest.locator(`[data-slot="2026-10-09/${t}"]`).tap();
  await expect(guest.getByText('내 가능 시간이 자동 저장되었어요.')).toBeVisible();
  await guest.reload(); await expect(guest.locator('[data-slot="2026-10-09/840"]')).toHaveAttribute('aria-pressed','true');
  await guest.locator('[data-slot="2026-10-09/960"]').tap();
  await expect(guest.getByText('내 가능 시간이 자동 저장되었어요.')).toBeVisible();
  await guest.screenshot({path:'test-results/time-mobile.png',fullPage:true});
  expect(await guest.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await guest.getByRole('link',{name:'장소',exact:true}).click();
  await guest.getByRole('button',{name:'장소 후보 추가'}).click();
  await guest.getByLabel('장소 이름',{exact:true}).fill('연남동 작은 식탁');
  await guest.getByRole('checkbox', {name:'지도 링크 만들기'}).check();
  await guest.getByLabel('짧은 설명').fill('이야기 나누기 좋은 조용한 곳');
  await guest.getByRole('button',{name:'후보 추가하기'}).click();
  await guest.getByRole('checkbox',{name:'연남동 작은 식탁 선택'}).check();
  await guest.getByRole('button',{name:'내 투표 저장'}).click(); await expect(guest.getByText('현재 1명 투표')).toBeVisible();
  await guest.getByRole('checkbox',{name:'연남동 작은 식탁 선택'}).uncheck(); await guest.getByRole('button',{name:'내 투표 저장'}).click(); await expect(guest.getByText('현재 0명 투표')).toBeVisible();
  await guest.getByRole('checkbox',{name:'연남동 작은 식탁 선택'}).check(); await guest.getByRole('button',{name:'내 투표 저장'}).click(); await expect(guest.getByText('현재 1명 투표')).toBeVisible();
  await page.getByRole('button',{name:'전체 현황',exact:true}).click(); await page.getByRole('button',{name:'현황 새로고침'}).click();
  await page.locator('[data-recommendation="all"] summary').click();
  await expect(page.locator('[data-recommendation="all"] .candidate').first()).toBeVisible();
  await page.getByRole('button',{name:'모임 시간 정하기',exact:true}).click();
  await page.locator('[data-slot="2026-10-09/840"]').click(); await expect(page.locator('.chosen-time')).toContainText('2 / 2명');
  await page.screenshot({path:'test-results/time-desktop.png',fullPage:true});
  await expect(page.locator('.confirmation-cell')).toHaveCount(4);
  await page.getByRole('button',{name:'이 시간으로 확정',exact:true}).click(); await page.getByRole('button',{name:'확인하고 저장'}).click();
  await page.getByRole('link',{name:'모임 홈',exact:true}).click(); await expect(page.getByText('시간 확정',{exact:true})).toBeVisible(); await expect(page.getByText('장소 정하는 중',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'장소',exact:true}).click(); await page.getByRole('button',{name:'이 장소 확정'}).click(); await page.getByRole('button',{name:'확인하고 저장'}).click();
  await guest.goto(url); await expect(guest.getByText('장소 확정',{exact:true})).toBeVisible(); await expect(guest.getByText('시간 확정',{exact:true})).toBeVisible();
  await guest.screenshot({path:'test-results/final-mobile.png',fullPage:true});
  await guest.goto('/m/not-a-real-link'); await expect(guest.getByRole('heading',{name:'모임을 불러오지 못했어요.'})).toBeVisible();
  expect(errors).toEqual([]); await mobile.close();
});
