import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1100,height:900}});
const m={id:'places-test',title:'장소 기능 확인',startDate:'2026-10-02',endDate:'2026-10-03',startMinute:540,endMinute:1320,duration:120,placeMode:'together',revision:1};
let places=[{id:'mine',name:'내 후보',address:'서울 성북구 정릉로 77',note:'',count:1,canEdit:true},{id:'other',name:'다른 사람 후보',address:'서울',count:0,canEdit:false}];
await page.route('**/api/**',async route=>{const r=route.request(),path=new URL(r.url()).pathname;let data={ok:true};if(path==='/api/me')data={user:{name:'테스트',id:'u'}};else if(path.endsWith('/places/mine')&&r.method()==='PATCH')Object.assign(places[0],r.postDataJSON().place);else if(path.endsWith('/places/mine')&&r.method()==='DELETE')places=places.filter(p=>p.id!=='mine');else if(path==='/api/meetings/places-test')data={meeting:m,places,myVotes:[],mine:{id:'u',name:'테스트',slots:[]},participants:[],responses:[],result:{total:0},isOwner:false};await route.fulfill({json:data});});
await page.goto('http://localhost:3000/m/places-test/place');
await expect(page.getByRole('button',{name:'수정',exact:true})).toHaveCount(1);
await page.getByRole('button',{name:'수정',exact:true}).click();
await expect(page.locator('input[name=address]')).toHaveAttribute('required','');
await page.locator('input[name=placeName]').fill('수정된 후보');
await page.getByRole('button',{name:'수정 저장'}).click();
await expect(page.getByRole('heading',{name:'수정된 후보'})).toBeVisible();
await page.getByRole('button',{name:'삭제',exact:true}).click();
await page.getByRole('button',{name:'후보 삭제',exact:true}).click();
await expect(page.getByRole('heading',{name:'수정된 후보'})).toHaveCount(0);
await expect(page.getByRole('heading',{name:'다른 사람 후보'})).toBeVisible();
await page.getByRole('button',{name:'장소 후보 추가'}).click();
await expect(page.getByRole('link',{name:'네이버 지도에서 장소 찾기'})).toHaveAttribute('href','https://map.naver.com/');
await page.screenshot({path:'test-results/place-edit.png',fullPage:true});
await browser.close();console.log('PASS: place author controls, editing, deletion, required address and Naver link');
