import React, { useState, useEffect, useRef } from 'react';
import { ArrowRight, ArrowUpRight, Check, CalendarBlank, Clock, MapPin, Copy, ArrowLeft, Users, GearSix } from '@phosphor-icons/react';
import { api } from './api';
import { Link, Button, Notice, Status, PlaceAddress, shortDate } from './ui';
import { durationLabel, clock } from '../shared/time';
import { MeetingForm } from './form';
import { TimeView } from './time';
import { Participants } from './participants';
import { PlaceView } from './place';
export function Meeting({ id, view, user }) {
  const [data, setData] = useState(null), [error, setError] = useState(''), [message, setMessage] = useState(''), [pending, setPending] = useState(null), [busy, setBusy] = useState(false);
  const load = async () => { await api(`/meetings/${id}/join`, 'POST', {}); const d = await api(`/meetings/${id}`); setData(d); setError(''); return d; };
  useEffect(() => { load().catch(e => setError(e.message)); }, [id, view, user?.id]);
  const action = async (path, body) => { await api(`/meetings/${id}/${path}`, 'POST', { ...body, revision: data.meeting.revision }); await load(); };
  if (!data) return <div className="empty">{error ? <><h1>모임을 불러오지 못했어요.</h1><Notice error>{error}</Notice><Button secondary onClick={() => load().catch(e => setError(e.message))}>다시 불러오기</Button><Link to="/" className="text-link">홈으로 돌아가기</Link></> : <p>모임을 불러오는 중입니다.</p>}</div>;
  const m = data.meeting;
  if (view === 'edit') return data.isOwner ? <MeetingForm data={data} onSaved={load}/> : <div className="empty"><h1>주최자만 설정을 바꿀 수 있어요.</h1><Link to={`/m/${id}`} className="text-link">모임으로 돌아가기</Link></div>;
  const ask = (title, detail, path, body = {}) => setPending({ title, detail, path, body });
  return <div className={`meeting-page ${view === 'time' ? 'time-focused-page' : ''}`}><div className="meeting-topline"><Link to="/" className="back-link"><ArrowLeft size={17}/> 모임표 홈</Link><div className="inline-actions"><button className="text-link" onClick={async () => { try { await navigator.clipboard.writeText(`${location.origin}/m/${id}`); setMessage('초대 링크를 복사했어요. 함께 만날 사람에게 보내 주세요.'); } catch { setMessage(`이 주소를 복사해 주세요: ${location.origin}/m/${id}`); } }}><Copy size={17}/> 초대 링크 복사</button>{data.isOwner && <Link className="text-link" to={`/m/${id}/edit`}><GearSix size={17}/> 세팅 수정</Link>}</div></div><div className="meeting-heading"><div className="heading-meta"><Status>{data.isOwner ? '내가 만든 모임' : '함께하는 모임'}</Status></div><h1>{m.title}</h1>{view !== 'time' && m.description && <p className="meeting-description">{m.description}</p>}<div className="meeting-meta"><span><CalendarBlank/> {shortDate(m.startDate)}{m.endDate !== m.startDate && ` ~ ${shortDate(m.endDate)}`}</span><span><Clock/> {durationLabel(m.duration)}</span><span><Users/>현재 {data.result.total}명 응답</span></div></div><nav className="meeting-tabs" aria-label="모임 화면">{[['home', '모임 홈'], ['time', '시간'], ['place', '장소']].map(([v, text]) => <Link key={v} to={`/m/${id}${v === 'home' ? '' : `/${v}`}`} aria-current={view === v ? 'page' : undefined}>{text}{v === 'time' && m.finalizedTime && <Check size={15}/>} {v === 'place' && m.finalizedPlace && <Check size={15}/>}</Link>)}</nav><Notice>{message}</Notice><Notice error>{error}</Notice>{view === 'home' ? <MeetingHome data={data} reload={load} ask={ask}/> : view === 'time' ? <TimeView data={data} user={user} reload={load} ask={ask}/> : <PlaceView data={data} user={user} reload={load} ask={ask}/>}<ConfirmDialog pending={pending} busy={busy} close={() => setPending(null)} confirm={async () => { setBusy(true); try { await action(pending.path, pending.body); setPending(null); setMessage('변경 사항을 저장했어요.'); } catch (e) { setPending(null); setError(e.message); } finally { setBusy(false); } }}/></div>;
}
function ConfirmDialog({ pending, busy, close, confirm }) {
  const ref = useRef(null);
  useEffect(() => { if (pending && !ref.current.open) ref.current.showModal(); if (!pending && ref.current.open) ref.current.close(); }, [pending]);
  return <dialog ref={ref} onCancel={e => { e.preventDefault(); if (!busy) close(); }}><div className="dialog-body"><h2>{pending?.title}</h2><p>{pending?.detail}</p><div className="inline-actions"><Button secondary disabled={busy} onClick={close}>취소</Button><Button disabled={busy} onClick={confirm}>{busy ? '저장 중…' : '확인하고 저장'}</Button></div></div></dialog>;
}
function MeetingHome({ data: d, reload, ask }) {
  const m = d.meeting;
  return <><div className="home-layout"><section className="home-main"><h2>우리의 약속은</h2><div className="summary-row"><div className="summary-icon"><CalendarBlank size={26}/></div><div><Status done={!!m.finalizedTime}>{m.finalizedTime ? '시간 확정' : '시간 조율 중'}</Status><h3>{m.finalizedTime ? shortDate(m.finalizedTime.date) : 'When?'}</h3><p>{m.finalizedTime ? `${clock(m.finalizedTime.start)}${m.finalizedTime.end === null ? ' 시작 · 소요 시간 미정' : ` ~ ${clock(m.finalizedTime.end)} · ${durationLabel(m.duration)}`}` : d.result.total ? `현재 ${d.result.total}명의 응답을 모았어요.` : '첫 번째 가능한 시간을 남겨 주세요.'}</p><Link to={`/m/${m.id}/time`} className="text-link">{m.finalizedTime ? '시간 확인하기' : '시간 현황 보기'}<ArrowRight size={17}/></Link></div></div><div className="summary-row"><div className="summary-icon"><MapPin size={26}/></div><div><Status done={!!m.finalizedPlace}>{m.finalizedPlace ? '장소 확정' : m.placeMode === 'later' ? '장소 미정' : '장소 정하는 중'}</Status><h3>{m.finalizedPlace?.name || 'Where?'}</h3>{m.finalizedPlace ? <PlaceAddress address={m.finalizedPlace.address}/> : <p>{m.placeMode === 'together' ? `${d.places.length}개의 후보 · 갈 수 있는 곳에 투표해요.` : '주최자가 나중에 장소를 정할 예정이에요.'}</p>}<Link to={`/m/${m.id}/place`} className="text-link">{m.finalizedPlace ? '장소 확인하기' : '장소 후보 확인하기'}<ArrowRight size={17}/></Link></div></div></section><aside className="next-action"><span className="eyebrow">{m.finalizedTime && m.finalizedPlace ? '약속 준비 완료' : '이제 내 차례'}</span><h2>{m.finalizedTime ? '만날 시간을 정했어요.' : d.mine?.slots != null ? '시간을 남겨 주셨네요.' : '가능한 시간을 알려 주세요.'}</h2><p>{m.finalizedTime ? '확정된 날짜와 장소를 확인해 주세요.' : d.mine?.slots != null ? <>일정이 바뀌셨나요?<br/>저장한 응답은 언제든 수정할 수 있어요 !</> : '30분 단위로 선택하면 돼요. 모두의 시간을 한눈에 비교할 수 있어요.'}</p><Link to={`/m/${m.id}/time${m.finalizedTime ? '' : '?mode=mine'}`} className="button">{m.finalizedTime ? '확정 시간 확인' : d.mine?.slots != null ? '내 응답 확인·수정' : '가능한 시간 입력하기'}<ArrowRight size={18}/></Link>{m.placeMode === 'together' && !m.finalizedPlace && <Link to={`/m/${m.id}/place`} className="button secondary">장소 제안하고 투표하기 <ArrowUpRight size={17}/></Link>}<span className="small" hidden={d.isOwner}>가입 없이 참여 · 이 브라우저에서 내 응답 수정</span></aside></div><Participants data={d} reload={reload} ask={ask}/></>;
}
