import React, { useState, useEffect } from 'react';
import { ArrowRight, ArrowUpRight, Plus, Check, CalendarBlank } from '@phosphor-icons/react';
import { api } from './api';
import { Link, Button, Notice, Status, shortDate, go } from './ui';
import { DeleteMeeting } from './delete-meeting';
import { durationLabel } from '../shared/time';
export function Dashboard({ user }) {
  const [meetings, setMeetings] = useState(null), [error, setError] = useState('');
  const [deleting, setDeleting] = useState(null);
  const load = () => { setError(''); if (user) api('/meetings').then(setMeetings).catch(e => setError(e.message)); };
  useEffect(load, [user]);
  return <div className="dashboard"><section className="intro"><div><span className="eyebrow">날짜부터 장소까지, 모임표</span><h1>언제 볼까요?<br/><span className="accent">여기서 맞춰요.</span></h1><p>시간/장소를 쉽고 빠르게 정해요<br/>인원이 많더라도 색깔로 한눈에 알아볼 수 있어요</p><Link to={user ? '/new' : '/login?next=new'} className="button">새 모임 만들기 <Plus size={20}/></Link></div><div className="schedule-art" aria-label="서로의 시간이 겹쳐 하나의 약속이 되는 모임표 일러스트"><div className="art-top">우리 언제 볼까?<ArrowUpRight size={24}/></div><div className="art-days"><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span></div><div className="art-grid"><div className="art-strip strip-one"><span><strong>나</strong>의 시간</span></div><div className="art-strip strip-two"><span><strong>너</strong>의 시간</span></div><div className="art-strip strip-three"><span><strong>우리</strong>의 시간</span> <Check size={20} weight="bold"/></div></div><div className="art-bottom"><span>칸을 누르면, 약속이 정해져요</span></div></div></section><section className="meeting-list"><div className="section-title"><h2>{user ? '내 모임' : '약속을 정하는 짧은 순서'}</h2><span className="muted">{user ? meetings === null ? '' : `총 ${meetings.length}개의 모임` : '참여자는 로그인 없이 이용가능'}</span></div><Notice error>{error}</Notice>{error && <Button secondary onClick={load}>다시 불러오기</Button>}{user ? meetings === null ? !error && <p>모임 목록을 불러오는 중입니다.</p> : <div className="meeting-role-groups">{[{ owner: false, title: '참여자인 모임' }, { owner: true, title: '주최자인 모임' }].map(group => {
    const items = meetings.filter(m => m.isOwner === group.owner);
    return <section className="meeting-role-group" key={group.title} aria-label={group.title}><div className="section-title"><h3>{group.title}</h3><span className="muted">{items.length}개의 모임</span></div>{items.length ? items.map(m => <div className="meeting-list-item" key={m.id}><Link to={`/m/${m.id}`} className="meeting-row"><div className="meeting-row-info"><h3>{m.title}</h3><p>{shortDate(m.startDate)}부터 · {durationLabel(m.duration)}</p></div><span className="meeting-statuses"><Status done={!!m.finalizedTime}>{m.finalizedTime ? '시간 확정' : '시간 조율 중'}</Status>{m.placeMode !== 'later' && <Status done={!!m.finalizedPlace}>{m.finalizedPlace ? '장소 확정' : '장소 조율 중'}</Status>}</span><ArrowUpRight size={23}/></Link>{m.isOwner && <button type="button" className="meeting-delete" aria-label={`${m.title} 모임 삭제`} onClick={() => setDeleting(m)}>삭제</button>}</div>) : <div className="empty-inline"><CalendarBlank size={32}/><div><h3>{group.owner ? '첫 번째 모임을 만들어 보세요.' : '아직 참여한 모임이 없어요.'}</h3><p>{group.owner ? '초대 링크 하나로 서로의 일정을 모을 수 있어요.' : '로그인한 상태로 초대 링크에 참여하면 여기에 표시돼요.'}</p></div>{group.owner && <Link to="/new" className="text-link">모임 만들기 <ArrowRight/></Link>}</div>}</section>;
  })}</div> : <div className="steps"><div><span>01</span><h3>모임을 만들고</h3><p>날짜와 시간을 조율할 범위를 정해요.</p></div><div><span>02</span><h3>링크로 초대하고</h3><p>이름과 가능한 시간을 편하게 남겨요.</p></div><div><span>03</span><h3>함께 정해요</h3><p>모인 응답을 보고 시간과 장소를 확정해요.</p></div></div>}</section>{deleting && <DeleteMeeting meeting={deleting} close={() => setDeleting(null)} onDeleted={id => { setMeetings(current => current.filter(m => m.id !== id)); setDeleting(null); }}/>}</div>;
}
export function Auth({ onLogin, next }) {
  const [register, setRegister] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  return <div className="auth-layout"><div className="auth-heading"><span className="eyebrow">약속의 시작</span><h1>만남을 여는<br/>당신을 위해.</h1><p>주최자만 로그인하면 돼요.<br/>초대받은 사람은 링크로 바로 참여해요.</p></div><form className="auth-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { const body = Object.fromEntries(new FormData(e.currentTarget)); const d = await api(`/auth/${register ? 'register' : 'login'}`, 'POST', body); onLogin(d.user); go(next || (location.search.includes('next=new') ? '/new' : '/')); } catch (e) { setError(e.message); } finally { setBusy(false); } }}><h2>{register ? '주최자 계정 만들기' : '주최자 로그인'}</h2>{register && <label>이름<input name="name" autoComplete="name" required maxLength={40}/></label>}<label>이메일<input type="email" name="email" autoComplete="email" required maxLength={254} placeholder="hello@example.com"/></label><label>비밀번호<input type="password" name="password" autoComplete={register ? 'new-password' : 'current-password'} minLength={10} maxLength={128} required placeholder="10자 이상 입력해 주세요"/></label><Notice error>{error}</Notice><Button disabled={busy} type="submit">{busy ? '확인 중…' : register ? '계정 만들기' : '로그인'}<ArrowRight size={18}/></Button><button type="button" className="text-link" onClick={() => { setRegister(!register); setError(''); }}>{register ? '이미 계정이 있나요? 로그인' : '처음 오셨나요? 계정 만들기'}</button><p className="small muted">이메일·비밀번호로 로그인합니다. 현재 이메일 인증과 비밀번호 재설정 메일은 제공하지 않아요.</p></form></div>;
}
